language: go

go:
  - 1.9.x

before_install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/mattn/goveralls
  - go get github.com/golang/dep/cmd/dep
  - go get github.com/ethereum/go-ethereum
  - dep ensure

script:
  - cd ethereum
  - ginkgo -v --trace --race --cover --coverprofile coverprofile.out
  - cd ../
  
after_success:
- goveralls -coverprofile=ethereum/coverprofile.out -service=travis-ci -repotoken $COVERALLS_TOKEN
