language: go

go:
  - 1.9.x

before_install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/mattn/goveralls
  - go get github.com/golang/dep/cmd/dep
  - go get github.com/golang/lint/golint
  - dep ensure

script:
  - go vet ./...
  - golint -set_exit_status `go list ./... | grep -v /vendor/`
  - ginkgo -v --trace --race --cover --coverprofile coverprofile.out
  - ginkgo -v --trace --race --cover --coverprofile coverprofile.out dark-node
  - ginkgo -v --trace --race --cover --coverprofile coverprofile.out identity
  - ginkgo -v --trace --race --cover --coverprofile coverprofile.out logger
  - ginkgo -v --trace --race --cover --coverprofile coverprofile.out network/dht
  - ginkgo -v --trace --race --cover --coverprofile coverprofile.out network/rpc
  - ginkgo -v --trace --race --cover --coverprofile coverprofile.out network
  - ginkgo -v --trace --race --cover --coverprofile coverprofile.out orders
  - ginkgo -v --trace --race --cover --coverprofile coverprofile.out shamir
  - ginkgo -v --trace --race --cover --coverprofile coverprofile.out stackint
  - sed -i '/rpc.pb.go/d' network/rpc/coverprofile.out
  
after_success:
  - goveralls -coverprofile=coverprofile.out -service=travis-ci -repotoken $COVERALLS_TOKEN
